// Bloodline Acres - Breed Photo URLs
// Auto-generated from TheDogAPI, AKC, and other sources
var BREED_PHOTOS = {
  "Affenpinscher": "https://storage.googleapis.com/dog-api-uploads-prod/originals/8009d9ca-3f02-41dc-89fd-c9241027fb96.jpeg",
  "Afghan Hound": "https://storage.googleapis.com/dog-api-uploads-prod/originals/4a361a1f-efa9-41a5-a164-124ca68ad141.jpeg",
  "Airedale Terrier": "https://cdn4.thedogapi.com/optimized/H5dFqyAoeZ.jpg",
  "Akbash": "https://cdn4.thedogapi.com/optimized/e8yVyPMX2w.jpg",
  "Akita Inu": "https://storage.googleapis.com/dog-api-uploads-prod/originals/85a7180d-7fab-42d6-b872-2f01fdae7ecb.jpeg",
  "Akita Inu (American)": "https://storage.googleapis.com/dog-api-uploads-prod/originals/85a7180d-7fab-42d6-b872-2f01fdae7ecb.jpeg",
  "Alaskan Malamute": "https://storage.googleapis.com/dog-api-uploads-prod/originals/4b2b5ed6-e152-4dfc-876e-0043914c7fef.jpeg",
  "Alaunt": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Gaston_Febus_Livre_de_la_chasse_alaunts.jpg/320px-Gaston_Febus_Livre_de_la_chasse_alaunts.jpg",
  "American Akita": "https://storage.googleapis.com/dog-api-uploads-prod/originals/85a7180d-7fab-42d6-b872-2f01fdae7ecb.jpeg",
  "American Bulldog": "https://storage.googleapis.com/dog-api-uploads-prod/originals/6bc0b248-c54b-480e-97ea-fb1f628d0f0e.jpeg",
  "American Cocker Spaniel": "https://cdn4.thedogapi.com/optimized/IKwhmJWCwN.jpg",
  "American English Coonhound": "https://www.akc.org/wp-content/uploads/2017/11/American-English-Coonhound-howling-in-a-field1.jpg",
  "American Eskimo Dog": "https://storage.googleapis.com/dog-api-uploads-prod/originals/4b94b0a4-85bc-4861-a37e-dac76def6390.jpeg",
  "American Foxhound": "https://storage.googleapis.com/dog-api-uploads-prod/originals/73e69c96-34f1-4a31-a96d-c9c042ea975e.jpeg",
  "American Hairless Terrier": "https://www.akc.org/wp-content/uploads/2017/11/American-Hairless-Terrier-standing-in-the-grass-on-lead.jpg",
  "American Pit Bull Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/a728c8bc-2a50-4d54-a903-91e5ab416294.jpeg",
  "American Staffordshire Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/fae232c8-6b6a-4b93-9f8a-09d0339b2a48.jpeg",
  "American Water Spaniel": "https://cdn4.thedogapi.com/optimized/NCxW2X6eTX.jpg",
  "Anatolian Shepherd": "https://www.akc.org/wp-content/uploads/2017/11/Anatolian-Shepherd-Dog-On-White-01.jpg",
  "Appenzeller Sennenhund": "https://storage.googleapis.com/dog-api-uploads-prod/originals/2d8c642c-6f86-4275-bbba-a7f0a1c088f5.jpeg",
  "Armenian Gampr": "https://static.wixstatic.com/media/b10959_44682e9cc8164b44a4d053e89bf8efcb~mv2.jpg/v1/fill/w_2500,h_5359,al_c/b10959_44682e9cc8164b44a4d053e89bf8efcb~mv2.jpg",
  "Australian Cattle Dog": "https://storage.googleapis.com/dog-api-uploads-prod/originals/da91e705-2ef9-4e75-8b19-691d8f99935e.jpeg",
  "Australian Kelpie": "https://storage.googleapis.com/dog-api-uploads-prod/originals/e4eea683-60f7-4095-9dc1-d35458f1d9ac.jpeg",
  "Australian Shepherd": "https://storage.googleapis.com/dog-api-uploads-prod/originals/941d27a3-a346-4b56-bfed-a76d4ec745cd.jpeg",
  "Australian Stumpy Tail Cattle Dog": "https://www.akc.org/wp-content/uploads/2018/07/GettyImages-454288321.jpg",
  "Australian Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/f264d025-4b87-4be4-bf4d-8c7fbb327773.jpeg",
  "Azawakh": "https://cdn4.thedogapi.com/optimized/kDnvvUI63Z.jpg",
  "Barbet": "https://cdn4.thedogapi.com/optimized/xFJkKsMcEB.jpg",
  "Basenji": "https://cdn4.thedogapi.com/optimized/1mYNTc1R6H.jpg",
  "Basset Hound": "https://storage.googleapis.com/dog-api-uploads-prod/originals/74b9e98d-60c5-484d-ad62-4db57a0bc47e.jpeg",
  "Bavarian Mountain Hound": "https://www.akc.org/wp-content/uploads/2017/11/Bavarian.190758538.jpg",
  "Beagle": "https://storage.googleapis.com/dog-api-uploads-prod/originals/076906f8-69d2-41be-957b-9542e1e36bbc.jpeg",
  "Bearded Collie": "https://storage.googleapis.com/dog-api-uploads-prod/originals/9840e3d7-0620-4702-a234-0c173d9ec304.jpeg",
  "Beauceron": "https://storage.googleapis.com/dog-api-uploads-prod/originals/088fe40b-4fac-4bf7-a875-26a1738e744d.jpeg",
  "Bedlington Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/3c9deb26-4c93-4dd0-86db-17e45ba11de3.jpeg",
  "Belgian Groenendael": "https://storage.googleapis.com/dog-api-uploads-prod/originals/e197d407-3e8d-4edd-adb7-daac0a4214fc.png",
  "Belgian Laekenois": "https://www.akc.org/wp-content/uploads/2017/11/Belgian-Laekenois-standing-in-profile-in-a-field.jpg",
  "Belgian Malinois": "https://storage.googleapis.com/dog-api-uploads-prod/originals/e197d407-3e8d-4edd-adb7-daac0a4214fc.png",
  "Belgian Tervuren": "https://storage.googleapis.com/dog-api-uploads-prod/originals/0c0410c2-7267-4734-a076-e152a1b8d396.jpeg",
  "Bergamasco Sheepdog": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/28124755/Bergamasco-Sheepdog-standing-in-a-field-in-the-mountains.jpg",
  "Berger Picard": "https://www.akc.org/wp-content/uploads/2017/11/Berger-Picard-standing-in-a-field.jpg",
  "Bernese Mountain Dog": "https://cdn4.thedogapi.com/optimized/givys4YtVB.jpg",
  "Bichon Frisé": "https://storage.googleapis.com/dog-api-uploads-prod/originals/35738179-7493-4377-b52e-3b8387e1a532.jpeg",
  "Biewer Terrier": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/14124534/Biewer-Terrier-standing-on-a-white-background1.jpg",
  "Black Mouth Cur": "https://www.akc.org/wp-content/uploads/2017/11/Black-Mouth-Cur-standing-in-a-field.jpg",
  "Black Russian Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Black-Russian-Terrier-standing-outdoors.jpg",
  "Bloodhound": "https://storage.googleapis.com/dog-api-uploads-prod/originals/2f5d5e94-a9ae-4d58-a781-ed685181997a.jpeg",
  "Blue Lacy": "https://dogtime.com/wp-content/uploads/sites/12/2023/09/GettyImages-173549958.jpg?resize=1200,630",
  "Bluetick Coonhound": "https://cdn4.thedogapi.com/optimized/ajTVVTrLne.jpg",
  "Boerboel": "https://cdn4.thedogapi.com/optimized/RIFlrU0fUA.jpg",
  "Bolognese": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/24113424/Bolognese-together-on-a-patio-chair-in-the-shade.jpg",
  "Border Collie": "https://storage.googleapis.com/dog-api-uploads-prod/originals/7ac26a12-d3bd-4939-a417-cf77f414fb0d.jpeg",
  "Border Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/6fcf6ce9-b2df-45c0-b154-1317df7b6c2c.jpeg",
  "Borzoi": "https://www.akc.org/wp-content/uploads/2017/11/Borzoi-running-outdoors.jpg",
  "Boston Terrier": "https://cdn4.thedogapi.com/optimized/0JqHiVXBhZ.jpg",
  "Bouvier des Flandres": "https://storage.googleapis.com/dog-api-uploads-prod/originals/be25309f-6190-40c9-b5b5-02630f873592.png",
  "Boxer": "https://cdn4.thedogapi.com/optimized/uFPUHEvbID.jpg",
  "Boykin Spaniel": "https://cdn4.thedogapi.com/optimized/i3VwMxfPgP.jpg",
  "Bracco Italiano": "https://cdn4.thedogapi.com/optimized/Sewp0Ubej3.jpg",
  "Briard": "https://cdn4.thedogapi.com/optimized/QHeak9hrOm.jpg",
  "Brittany Spaniel": "https://storage.googleapis.com/dog-api-uploads-prod/originals/7d55f697-6879-4616-af9d-668aa3226289.jpeg",
  "Broholmer": "https://www.akc.org/wp-content/uploads/2017/11/Broholmer-laying-down-in-the-park.jpg",
  "Brussels Griffon": "https://www.akc.org/wp-content/uploads/2017/11/Brussels-Griffon-sitting-outdoors.jpg",
  "Bull Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/19be57ef-e967-4330-81f3-83a7c1ac809c.jpeg",
  "Bulldog": "https://storage.googleapis.com/dog-api-uploads-prod/originals/7fce7584-ce26-4b07-ac50-00917f685ea3.jpeg",
  "Bullmastiff": "https://cdn4.thedogapi.com/optimized/QdwFluBnbf.jpg",
  "Cairn Terrier": "https://cdn4.thedogapi.com/optimized/AEtWWjCcLL.jpg",
  "Canaan Dog": "https://www.akc.org/wp-content/uploads/2017/11/Canaan-Dog-On-White-01.jpg",
  "Canadian Eskimo Dog": "https://www.akc.org/wp-content/uploads/2025/01/Canadian-Eskimo-Dog-playing-yard.jpg",
  "Cane Corso": "https://storage.googleapis.com/dog-api-uploads-prod/originals/10d8fcaf-a0dd-4988-9e69-54002e3c4f83.png",
  "Cardigan Welsh Corgi": "https://storage.googleapis.com/dog-api-uploads-prod/originals/3c664674-c538-4c15-bab4-6ae3096dbcfb.png",
  "Carpathian Shepherd Dog": "https://cdn-fastly.petguide.com/media/2022/02/16/8239567/carpathian-shepherd-dog.jpg?size=1200x628",
  "Catalan Sheepdog": "https://cdn-fastly.petguide.com/media/2022/02/16/8219765/catalan-sheepdog.jpg?size=1200x628",
  "Caucasian Ovcharka": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kavkazskaya_Ovcharka.jpg/320px-Kavkazskaya_Ovcharka.jpg",
  "Cavalier King Charles Spaniel": "https://cdn4.thedogapi.com/optimized/fM3yF6cLB1.jpg",
  "Central Asian Shepherd": "https://www.akc.org/wp-content/uploads/2017/11/Central-Asian-Shepherd-Dog-on-White-02.jpg",
  "Cesky Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Cesky-Terrier-on-White-011.jpg",
  "Chesapeake Bay Retriever": "https://cdn4.thedogapi.com/optimized/MLiMZc2OS4.jpg",
  "Chihuahua": "https://www.akc.org/wp-content/uploads/2017/11/Chihuahua-standing-in-three-quarter-view.jpg",
  "Chinese Crested": "https://cdn4.thedogapi.com/optimized/EmZBU7gxxa.jpg",
  "Chinook": "https://cdn4.thedogapi.com/optimized/LtHPr7ay0L.jpg",
  "Chow Chow": "https://cdn4.thedogapi.com/optimized/XSu9Ht84DA.jpg",
  "Chow Chow (Smooth)": "https://cdn4.thedogapi.com/optimized/XSu9Ht84DA.jpg",
  "Cirneco dell'Etna": "https://www.akc.org/wp-content/uploads/2017/11/Cirneco-dellEtna-hunting.jpg",
  "Clumber Spaniel": "https://cdn4.thedogapi.com/optimized/M5cp3u9VBx.jpg",
  "Coonhound (Black & Tan)": "https://storage.googleapis.com/dog-api-uploads-prod/originals/67602199-27c1-4ccb-8b7b-fc724809c63b.jpeg",
  "Coton de Tulear": "https://cdn4.thedogapi.com/optimized/mFiuFIyvhH.jpg",
  "Croatian Sheepdog": "https://www.akc.org/wp-content/uploads/2018/05/Croatian-Sheepdog.jpg",
  "Curly-Coated Retriever": "https://www.akc.org/wp-content/uploads/2017/11/Curly-Coated-Retriever-standing-stacked-in-a-field-at-sunset.20200418030641387.jpg",
  "Czechoslovakian Vlcak": "https://www.akc.org/wp-content/uploads/2017/11/Czechoslovakian-Vlcak.179296809.jpg",
  "Dachshund": "https://www.akc.org/wp-content/uploads/2017/11/Longhaired-Dachshund-standing-outdoors.jpg",
  "Dalmatian": "https://cdn4.thedogapi.com/optimized/ACDtQWVRBr.jpg",
  "Dandie Dinmont Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Dandie-Dinmont-Terrier-slide-6.jpg",
  "Doberman Pinscher": "https://cdn4.thedogapi.com/optimized/yy1nVxX1TD.jpg",
  "Dogo Argentino": "https://cdn4.thedogapi.com/optimized/TKneriCOWC.jpg",
  "Dogue de Bordeaux": "https://www.akc.org/wp-content/uploads/2017/11/Dogue-de-Bordeaux-On-White-03.jpg",
  "Dutch Shepherd": "https://cdn4.thedogapi.com/optimized/GxmoWNpZqN.jpg",
  "English Cocker Spaniel": "https://cdn4.thedogapi.com/optimized/OIR28n2ihA.jpg",
  "English Mastiff": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12230849/Mastiff-On-White-03.jpg",
  "English Pointer": "https://cdn4.thedogapi.com/optimized/A7aYZ5fINU.jpg",
  "English Setter": "https://cdn4.thedogapi.com/optimized/DaCvmFBDVI.jpg",
  "English Shepherd": "https://cdn4.thedogapi.com/optimized/cb5ROjCCNf.jpg",
  "English Springer Spaniel": "https://cdn4.thedogapi.com/optimized/AT2BZ19dCG.jpg",
  "English Toy Terrier": "https://cdn4.thedogapi.com/optimized/gS4U8SIVh6.jpg",
  "Entlebucher Mountain Dog": "https://www.akc.org/wp-content/uploads/2017/11/Entlebucher-Mountain-Dog-outdoors-standing-in-a-field.jpg",
  "Estrela Mountain Dog": "https://www.akc.org/wp-content/uploads/2017/11/Beau.jpg",
  "Eurasier": "https://cdn4.thedogapi.com/optimized/hZkMlKOLPl.jpg",
  "Field Spaniel": "https://cdn4.thedogapi.com/optimized/Be3GbWbcKe.jpg",
  "Fila Brasileiro": "https://articles.hepper.com/wp-content/uploads/2023/07/fila-brasileiro-dog-standing_Julia-Siomuha-Shutterstock.jpg",
  "Finnish Lapphund": "https://cdn4.thedogapi.com/optimized/iYYvYN0MXl.jpg",
  "Finnish Spitz": "https://cdn4.thedogapi.com/optimized/0nn8e8rJH2.jpg",
  "Flat-Coated Retriever": "https://www.akc.org/wp-content/uploads/2017/11/Flat-Coated-Retrievers-sitting-outdoors.jpg",
  "Fox Terrier (Smooth)": "https://cdn4.thedogapi.com/optimized/lhpcfYROeC.jpg",
  "Fox Terrier (Wire)": "https://cdn4.thedogapi.com/optimized/lYxCEtfMI1.jpg",
  "Foxhound": "https://storage.googleapis.com/dog-api-uploads-prod/originals/73e69c96-34f1-4a31-a96d-c9c042ea975e.jpeg",
  "French Bulldog": "https://cdn4.thedogapi.com/optimized/Rvl1BeqaRB.jpg",
  "GSD American Show": "https://cdn4.thedogapi.com/optimized/kc6oAx2b3X.jpg",
  "GSD Czech Working": "https://cdn4.thedogapi.com/optimized/kc6oAx2b3X.jpg",
  "GSD DDR East German": "https://cdn4.thedogapi.com/optimized/kc6oAx2b3X.jpg",
  "GSD West German Show": "https://cdn4.thedogapi.com/optimized/kc6oAx2b3X.jpg",
  "GSD West German Working": "https://cdn4.thedogapi.com/optimized/kc6oAx2b3X.jpg",
  "German Longhaired Pointer": "https://cdn4.thedogapi.com/optimized/A7aYZ5fINU.jpg",
  "German Shepherd": "https://cdn4.thedogapi.com/optimized/kc6oAx2b3X.jpg",
  "German Shorthaired Pointer": "https://cdn4.thedogapi.com/optimized/A7aYZ5fINU.jpg",
  "German Spitz (Klein)": "https://cdn4.thedogapi.com/optimized/a9bVhDxsQC.jpg",
  "German Spitz (Mittel)": "https://cdn4.thedogapi.com/optimized/a9bVhDxsQC.jpg",
  "German Wirehaired Pointer": "https://cdn4.thedogapi.com/optimized/fMSaUQg2IP.jpg",
  "Giant Schnauzer": "https://cdn4.thedogapi.com/optimized/Ygv4UKHpCW.jpg",
  "Glen of Imaal Terrier": "https://cdn4.thedogapi.com/optimized/lzq3JY4LXN.jpg",
  "Golden Retriever": "https://cdn4.thedogapi.com/optimized/X9w40D9ojT.jpg",
  "Gordon Setter": "https://cdn4.thedogapi.com/optimized/GFuEqzH0Fq.jpg",
  "Grand Basset Griffon Vendéen": "https://www.akc.org/wp-content/uploads/2017/11/GBGV.2.jpg",
  "Great Dane": "https://cdn4.thedogapi.com/optimized/MmjpsRG5IG.jpg",
  "Great Pyrenees": "https://storage.googleapis.com/dog-api-uploads-prod/originals/1b8f2066-261d-46d4-a358-23f61edc5d1a.png",
  "Greater Swiss Mountain Dog": "https://www.akc.org/wp-content/uploads/2017/11/Greater-Swiss-Mountain-Dog-laying-down-in-the-grass.jpg",
  "Greenland Dog": "https://cdn-fastly.petguide.com/media/2022/02/16/8218388/greenland-dog.jpg?size=1200x628",
  "Greyhound": "https://cdn4.thedogapi.com/optimized/fVVxWR2qse.jpg",
  "Harrier": "https://cdn4.thedogapi.com/optimized/6H9mhrLwdk.jpg",
  "Havanese": "https://cdn4.thedogapi.com/optimized/8bzLyVs2dA.jpg",
  "Hokkaido": "https://www.akc.org/wp-content/uploads/2017/11/Hokkaido.1.jpg",
  "Hovawart": "https://www.akc.org/wp-content/uploads/2017/11/Hovawart.10.jpg",
  "Hungarian Greyhound": "https://cdn4.thedogapi.com/optimized/fVVxWR2qse.jpg",
  "Ibizan Hound": "https://www.akc.org/wp-content/uploads/2017/11/Ibizan-Hound-sitting-in-profile-in-the-desert.jpg",
  "Icelandic Sheepdog": "https://www.akc.org/wp-content/uploads/2017/11/Icelandic-Sitting.jpg",
  "Irish Red & White Setter": "https://www.akc.org/wp-content/uploads/2017/11/Irish-Red-and-White-Setter-stalking-in-a-field.jpg",
  "Irish Setter": "https://cdn4.thedogapi.com/optimized/wWecmugBdH.jpg",
  "Irish Terrier": "https://cdn4.thedogapi.com/optimized/pVmDXiYLCl.jpg",
  "Irish Water Spaniel": "https://www.akc.org/wp-content/uploads/2017/11/Irish-Water-Spaniel-On-White-01.jpg",
  "Irish Wolfhound": "https://cdn4.thedogapi.com/optimized/s2EMPFktdk.jpg",
  "Italian Greyhound": "https://cdn4.thedogapi.com/optimized/dn8F4NPRdX.jpg",
  "Jack Russell Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Russell-Terrier-On-White-03.jpg",
  "Jagdterrier": "https://www.akc.org/wp-content/uploads/2017/11/Jagdterrier.4.jpg",
  "Japanese Chin": "https://cdn4.thedogapi.com/optimized/1TlHrdv5SQ.jpg",
  "Jindo": "https://cdn-fastly.petguide.com/media/2022/02/16/8212337/korean-jindo.jpg?size=1200x628",
  "Kangal": "https://cdn4.thedogapi.com/optimized/sQrQ6sVszv.jpg",
  "Karelian Bear Dog": "https://www.akc.org/wp-content/uploads/2017/11/Karelian-Bear-Dog.jpg",
  "Keeshond": "https://cdn4.thedogapi.com/optimized/ZpfPWRzZjj.jpg",
  "Kerry Blue Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Kerry-Blue-Terrier-standing-stacked-outdoors.jpg",
  "King Charles Spaniel": "https://cdn4.thedogapi.com/optimized/MT3wm2MmFG.jpg",
  "King Shepherd": "https://images.wagwalkingweb.com/media/breed/king-shepherd/hero/King-Shepherd.jpg",
  "Komondor": "https://cdn4.thedogapi.com/optimized/vutXumi0ih.jpg",
  "Kooikerhondje": "https://cdn4.thedogapi.com/optimized/hrBH92kypI.jpg",
  "Kurdish Mastiff Pshdar": "https://www.101dogbreeds.com/wp-content/uploads/2022/10/crossbreeds-icon.png",
  "Kuvasz": "https://cdn4.thedogapi.com/optimized/TpZNIKNjnH.jpg",
  "Labrador Retriever": "https://cdn4.thedogapi.com/optimized/BE5AcsNMdm.jpg",
  "Lagotto Romagnolo": "https://cdn4.thedogapi.com/optimized/YwlHg9x5AL.jpg",
  "Lakeland Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Lakeland-Terrier-standing-stacked-outdoors.jpg",
  "Leonberger": "https://cdn4.thedogapi.com/optimized/EtmEHVP7o1.jpg",
  "Lhasa Apso": "https://cdn4.thedogapi.com/optimized/QTZrK5N6RA.jpg",
  "Louisiana Catahoula Leopard": "https://cdn4.thedogapi.com/optimized/Q1BZEKatoN.jpg",
  "Löwchen": "https://www.akc.org/wp-content/uploads/2017/11/Lowchen-at-the-AKC-National-Championship-presented-by-Royal-Canin.jpg",
  "Maltese": "https://cdn4.thedogapi.com/optimized/6Kzt53hxrg.jpg",
  "Manchester Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Manchester-Terrier-Standard-on-White-08.jpg",
  "Maremma Sheepdog": "https://images.wagwalkingweb.com/media/breed/maremma-sheepdog/hero/Maremma-Sheepdog.jpg",
  "Miniature American Shepherd": "https://cdn4.thedogapi.com/optimized/azYjQgJT4i.jpg",
  "Miniature Bull Terrier": "https://storage.googleapis.com/dog-api-uploads-prod/originals/19be57ef-e967-4330-81f3-83a7c1ac809c.jpeg",
  "Miniature Pinscher": "https://cdn4.thedogapi.com/optimized/eEr2arSRx8.jpg",
  "Miniature Poodle": "https://storage.googleapis.com/dog-api-uploads-prod/originals/26157129-e8cc-44a1-bbb1-cec578a5f3d7.png",
  "Miniature Schnauzer": "https://cdn4.thedogapi.com/optimized/28pSRwqLJd.jpg",
  "Mountain Cur": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12191148/Mountain-Cur-MP.jpg",
  "Mudi": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/03140458/Mudi-sitting-outdoors.jpg",
  "Neapolitan Mastiff": "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2009/01/26133242/Neapolitan-Mastiff-on-lead-standing-in-the-grass-outdoors.20190813025752970.jpg",
  "Newfoundland": "https://cdn4.thedogapi.com/optimized/XoNRi6HPSY.jpg",
  "Norfolk Terrier": "https://cdn4.thedogapi.com/optimized/aQ4ySqmNa3.jpg",
  "Northern Inuit": "https://images.wagwalkingweb.com/media/breed/northern-inuit/hero/Northern-Inuit.jpg",
  "Norwegian Buhund": "https://www.akc.org/wp-content/uploads/2017/11/Norwegian-Buhund-On-White-01.jpg",
  "Norwegian Elkhound": "https://www.akc.org/wp-content/uploads/2017/11/Norwegian-Elkhound-sitting-in-the-snow-looking-back-over-its-shoulder.jpg",
  "Norwich Terrier": "https://cdn4.thedogapi.com/optimized/D9NaMDkqnJ.jpg",
  "Nova Scotia Duck Tolling Retriever": "https://cdn4.thedogapi.com/optimized/hCcdtR8rVg.jpg",
  "Old English Sheepdog": "https://cdn4.thedogapi.com/optimized/XVygKfbKvg.jpg",
  "Olde English Bulldogge": "https://cdn4.thedogapi.com/optimized/NUF657Zjvh.jpg",
  "Otterhound": "https://www.akc.org/wp-content/uploads/2017/11/Otterhound-On-White-03.jpg",
  "Papillon": "https://cdn4.thedogapi.com/optimized/0qgmSrCbvZ.jpg",
  "Parson Russell Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Parson-Russell-Terrier-standing-in-three-quarter-view-on-a-white-background.jpg",
  "Patterdale Terrier": "https://dogtime.com/wp-content/uploads/sites/12/2020/10/GettyImages-1267342828.jpg?resize=1200,630",
  "Pekingese": "https://cdn4.thedogapi.com/optimized/QpW51pxyRk.jpg",
  "Pembroke Welsh Corgi": "https://cdn4.thedogapi.com/optimized/R33EpeVC4M.jpg",
  "Perro de Presa Canario": "https://cdn4.thedogapi.com/optimized/nF8GskKeDc.jpg",
  "Peruvian Inca Orchid": "https://www.akc.org/wp-content/uploads/2017/11/Peruvian-Inca-Orchid-04.jpg",
  "Pharaoh Hound": "https://cdn4.thedogapi.com/optimized/dIwJe77wP0.jpg",
  "Plott Hound": "https://cdn4.thedogapi.com/optimized/xqSZ5QgaTA.jpg",
  "Polish Lowland Sheepdog": "https://www.akc.org/wp-content/uploads/2017/11/Polish-Lowland-Sheepdog-On-White-02.jpg",
  "Pomeranian": "https://cdn4.thedogapi.com/optimized/zuTzCtrqg3.jpg",
  "Portuguese Sheepdog": "https://www.akc.org/wp-content/uploads/2017/11/Black-Portuguese-Sheepdog-standing-outdoors-in-the-grass.jpg",
  "Pug": "https://cdn4.thedogapi.com/optimized/sKx0rFHMRN.jpg",
  "Puli": "https://cdn4.thedogapi.com/optimized/BH8KAhIGvc.jpg",
  "Pumi": "https://cdn4.thedogapi.com/optimized/yJmx50juxq.jpg",
  "Pyrenean Mastiff": "https://www.akc.org/wp-content/uploads/2017/11/Pyrenean-Mastiff-On-White-01.jpg",
  "Pyrenean Shepherd": "https://www.akc.org/wp-content/uploads/2017/11/Pyrenean-Shepherd-standing-in-profile-in-a-field.jpg",
  "Rajapalayam": "https://www.dogbreedinfo.com../images26/RajapalayamPurebredDogIndiaTom1HalfYearsOld1.jpg",
  "Rat Terrier": "https://cdn4.thedogapi.com/optimized/mR1VeAsbKF.jpg",
  "Redbone Coonhound": "https://cdn4.thedogapi.com/optimized/9kvNw9tFVP.jpg",
  "Rhodesian Ridgeback": "https://cdn4.thedogapi.com/optimized/Q3DE5jQ8fR.jpg",
  "Rottweiler": "https://cdn4.thedogapi.com/optimized/LxI7Kkc5oH.jpg",
  "Rough Collie": "https://www.akc.org/wp-content/uploads/2017/11/Collie-standing-in-a-field.jpg",
  "Russian Toy": "https://cdn4.thedogapi.com/optimized/DXnBRzsNdw.jpg",
  "Russkiy Toy": "https://cdn4.thedogapi.com/optimized/DXnBRzsNdw.jpg",
  "Saarloos Wolfdog": "https://images.wagwalkingweb.com/media/breed/saarloos-wolfdog/hero/Saarloos-Wolfdog.jpg",
  "Saint Bernard": "https://cdn4.thedogapi.com/optimized/IcWEuLHtBn.jpg",
  "Saluki": "https://cdn4.thedogapi.com/optimized/XEsp2dsjPM.jpg",
  "Samoyed": "https://cdn4.thedogapi.com/optimized/bLkWhvuqNJ.jpg",
  "Sarabi Persian Mastiff": "https://www.dogster.com/wp-content/uploads/2024/03/Sarabi-Dog-Sitting-in-the-Green-Grass_Keyur-Trivedi_Shutterstock.jpg",
  "Sarmatian Mastiff": "https://www.101dogbreeds.com/wp-content/uploads/2022/10/crossbreeds-icon.png",
  "Schipperke": "https://cdn4.thedogapi.com/optimized/fWSbovpqXi.jpg",
  "Scottish Deerhound": "https://cdn4.thedogapi.com/optimized/i9G4f21V3R.jpg",
  "Scottish Terrier": "https://cdn4.thedogapi.com/optimized/KHqTyrsJV6.jpg",
  "Sealyham Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Sealyham-Terrier-standing-in-three-quarter-view.1.jpg",
  "Shetland Sheepdog": "https://cdn4.thedogapi.com/optimized/sed3BFUfdo.jpg",
  "Shiba Inu": "https://cdn4.thedogapi.com/optimized/tLV9uXVpog.jpg",
  "Shih Tzu": "https://cdn4.thedogapi.com/optimized/FpTUahuFwc.jpg",
  "Shikoku": "https://www.akc.org/wp-content/uploads/2017/11/Shikoku-standing-outdoors.jpg",
  "Shiloh Shepherd": "https://cdn4.thedogapi.com/optimized/ls767UKreG.jpg",
  "Siberian Husky": "https://cdn4.thedogapi.com/optimized/y8p3WCHoxH.jpg",
  "Silky Terrier": "https://cdn4.thedogapi.com/optimized/LX867UmLze.jpg",
  "Skye Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Skye-Terrier-standing-outdoors-in-profile.jpg",
  "Sloughi": "https://www.akc.org/wp-content/uploads/2017/11/Sloughi-in-the-desert.jpg",
  "Slovak Cuvac": "https://cdn-fastly.petguide.com/media/2022/02/16/8221094/slovak-cuvac.jpg?size=1200x628",
  "Smooth Collie": "https://www.akc.org/wp-content/uploads/2017/11/Collie-standing-in-a-field.jpg",
  "Soft Coated Wheaten Terrier": "https://cdn4.thedogapi.com/optimized/ikOLxquC5T.jpg",
  "South African Boerboel Herder": "https://cdn4.thedogapi.com/optimized/RIFlrU0fUA.jpg",
  "Spanish Greyhound": "https://cdn4.thedogapi.com/optimized/fVVxWR2qse.jpg",
  "Spanish Mastiff": "https://www.akc.org/wp-content/uploads/2017/11/Spanish-Mastiff.jpg",
  "Spinone Italiano": "https://cdn4.thedogapi.com/optimized/AO4eNHKHfu.jpg",
  "Staffordshire Bull Terrier": "https://cdn4.thedogapi.com/optimized/zHMHibdcLN.jpg",
  "Standard Poodle": "https://www.akc.org/wp-content/uploads/2017/11/Standard-Poodle-standing-outdoors-at-the-beach.jpg",
  "Standard Schnauzer": "https://cdn4.thedogapi.com/optimized/nzjOKufQGP.jpg",
  "Sussex Spaniel": "https://www.akc.org/wp-content/uploads/2017/11/Sussex-Spaniel-On-White-01.jpg",
  "Swedish Vallhund": "https://cdn4.thedogapi.com/optimized/IfaS21KAcV.jpg",
  "Tamaskan": "https://articles.hepper.com/wp-content/uploads/2024/03/Tamaskan.jpg",
  "Thai Ridgeback": "https://cdn4.thedogapi.com/optimized/niUi2k5cdI.jpg",
  "Tibetan Mastiff": "https://cdn4.thedogapi.com/optimized/xmzLo9U9nV.jpg",
  "Tibetan Spaniel": "https://cdn4.thedogapi.com/optimized/Uz9mTebSzn.jpg",
  "Tibetan Terrier": "https://cdn4.thedogapi.com/optimized/YpsoizHqV5.jpg",
  "Tosa Inu": "https://www.akc.org/wp-content/uploads/2017/11/Tosa-on-White-01.jpg",
  "Toy Fox Terrier": "https://cdn4.thedogapi.com/optimized/5BVhG81gSe.jpg",
  "Treeing Tennessee Brindle": "https://www.akc.org/wp-content/uploads/2017/11/Treeing-Tennessee-Brindle-on-White-01.jpg",
  "Treeing Walker Coonhound": "https://cdn4.thedogapi.com/optimized/kGruq6EvlB.jpg",
  "Utonagan": "https://www.dogbreedinfo.com../images27/UtonaganPurebredDogs3YearsOldBonnieAndClyde.jpg",
  "Vizsla": "https://cdn4.thedogapi.com/optimized/UAHks1q5iR.jpg",
  "Weimaraner": "https://cdn4.thedogapi.com/optimized/oYrtCTqH9l.jpg",
  "Welsh Springer Spaniel": "https://cdn4.thedogapi.com/optimized/yRhKp8FeFn.jpg",
  "Welsh Terrier": "https://www.akc.org/wp-content/uploads/2017/11/Welsh-Terrier-standing-stacked-in-the-grass.jpg",
  "West Highland White Terrier": "https://cdn4.thedogapi.com/optimized/9Vh5N533hN.jpg",
  "Whippet": "https://cdn4.thedogapi.com/optimized/I9Bo3DVtQw.jpg",
  "White Swiss Shepherd": "https://cdn4.thedogapi.com/optimized/68ljzL8GYr.jpg",
  "Wirehaired Pointing Griffon": "https://cdn4.thedogapi.com/optimized/fMSaUQg2IP.jpg",
  "Wirehaired Vizsla": "https://cdn4.thedogapi.com/optimized/kjHLge9m58.jpg",
  "Xoloitzcuintli": "https://cdn4.thedogapi.com/optimized/owYeoJuOc7.jpg",
  "Yorkshire Terrier": "https://cdn4.thedogapi.com/optimized/EBxFXxL6xN.jpg",
};